from __future__ import annotations

from typing import Protocol


class Storage(Protocol):
    def setup(self) -> None: ...
    def append_order(self, order: dict[str, str]) -> dict[str, str]: ...
    def unpaid_orders(self) -> list[dict[str, str]]: ...
    def pending_delivery_orders(self) -> list[dict[str, str]]: ...
    def today_report(self) -> dict[str, int]: ...
    def get_user_language(self, telegram_user_id: int) -> str | None: ...
    def get_user_role(self, telegram_user_id: int) -> str | None: ...
    def set_user_language(
        self,
        telegram_user_id: int,
        username: str | None,
        first_name: str | None,
        language: str,
    ) -> None: ...
